auth_url: 'http://192.168.201.233:35357'
username: 'tacker'
password: 'password'
project_name: 'service'
project_domain_name: 'Default'
user_domain_name: 'Default'
cert_verify: 'True'
project_domain_name: 'Default'
user_domain_name: 'Default'
